# AUTOGENERATED! DO NOT EDIT! File to edit: ../01_deck.ipynb.

# %% auto 0
__all__ = ['Deck']

# %% ../01_deck.ipynb 2
from .card import *
from fastcore.utils import *
import random

# %% ../01_deck.ipynb 4
class Deck:
    def __init__(self): self.cards = [Card(s, r) for s in range(4) for r in range(1, 14)]
    def __len__(self): return len(self.cards)
    def __str__(self): return '; '.join(map(str, self.cards))
    def __contains__(self, card): return card in self.cards
    __repr__ = __str__

# %% ../01_deck.ipynb 12
@patch
def pop(self:Deck,
        idx:int=-1
       ): # The index of the card to remove, defaulting to the last one
    "Remove one card from the deck"
    return self.cards.pop(idx)
@patch
def remove(self:Deck,
          card:Card
          ): # Remove the `Card` from the `Deck`
    "Removes `card` from the deck or raises an exception if it is not there"
    self.cards.remove(card)
